### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MirandAlejandro** [sustained/dev.to-article-sources#1]
Greetings!
I was amazed by your article [https://dev.to/sustained/laravel-vue-4530](url). I was looking for a "guide for dummies" to make de fabulous Laravel 6 + Vuejs, so thank you!!!

Now the problem: In the point named "Lack of Webpack aliases when using Laravel Mix", the link to the plugin is broken. Just that.

**Comment by sustained** [comment]
For some reason they removed that extension from their website, I don't know why.

I think it was [this one](https://github.com/MaximVanhove/laravel-mix-alias).

**Comment by MirandAlejandro** [comment]
Thanks!
